-- Tareas: esquema inicial exportado desde el PostgreSQL de desarrollo.
-- Ejecutar este archivo una vez en Supabase > SQL Editor.

create table if not exists public.tasks (
  id integer generated by default as identity primary key,
  course text not null check (course in ('1A', '2A', '3A', '4A', '5A', '6A')),
  title text not null,
  description text not null default '',
  due_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_course_due_at_idx
  on public.tasks (course, due_at);

insert into public.tasks (
  id,
  course,
  title,
  description,
  due_at,
  created_at,
  updated_at
)
values
  (
    2,
    '4A',
    'Informe de ecosistemas',
    'Presentar una hoja sobre un ecosistema de Bolivia y sus especies representativas.',
    '2026-09-09T00:00:00Z',
    '2026-09-09T22:14:47.342834Z',
    '2026-09-09T22:14:47.342834Z'
  ),
  (
    3,
    '2A',
    'Prueba',
    'Prueba',
    '2026-09-11T12:50:00Z',
    '2026-09-09T22:22:59.688926Z',
    '2026-09-09T22:22:59.651Z'
  )
on conflict (id) do update set
  course = excluded.course,
  title = excluded.title,
  description = excluded.description,
  due_at = excluded.due_at,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

select setval(
  pg_get_serial_sequence('public.tasks', 'id'),
  greatest(coalesce((select max(id) from public.tasks), 1), 1),
  true
);